Phase8
ivahei/Restaurant pull request #3
Opened 2022-02-26 17:38 UTC by ivahei

finished phase 8 + bug fixes

2022-02-28 15:24 UTC, hovaks requested changes

2022-02-28 15:24 UTC, hovaks commented on Restaurant/Controller/Cells/OrderTableViewCell.swift
> +    override func awakeFromNib() {
իմաստը

2022-02-28 15:24 UTC, hovaks commented on Restaurant/Controller/Server Request/SubmitOrder.swift
> +        request.setValue("application/json", forHTTPHeaderField:
փնթոշ ա

2022-02-28 15:24 UTC, hovaks commented on Restaurant/Controller/View Controllers/CategoryTableViewController.swift
> +    override func numberOfSections(in tableView: UITableView) -> Int {
զաչեմ

2022-02-28 15:24 UTC, hovaks commented on Restaurant/Controller/View Controllers/MenuItemDetailViewController.swift
> +            animations: {
trailing closer արա էս

2022-02-28 15:24 UTC, hovaks commented on Restaurant/Controller/View Controllers/MenuTableViewController.swift
> +    override func numberOfSections(in tableView: UITableView) -> Int {
զաչեմ 2

2022-02-28 18:39 UTC, ivahei commented on Restaurant/Controller/Cells/OrderTableViewCell.swift
> +    override func awakeFromNib() {
չկա), 10-ում ջնջել էի

2022-03-10 18:30 UTC, hovaks approved these changes

2022-03-10 18:30 UTC, merged